config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "contentful_posts#index"

  resources :contentful_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contentful_posts_controller.rb
require 'contentful_post'
class ContentfulPostsController < ApplicationController
  before_action :contentfulPost_config

  def index
    @posts = @contentful_client.entries
  end

  def show
    @post = @contentful_client.entry(params[:id])
  end

  private

  def contentfulPost_config
    @contentful_client = ContentfulPost.configure
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contentful_posts/index.html.erb
<h1>Contentful Posts</h1>

<ul>
  <% @posts.each do |post| %>
  <% if post.fields[:photo] != nil %>
    <li>
      <%= post.fields[:title]%>
      <%= post.fields[:photo].fields[:url] %>
      <%= link_to "Detail", contentful_post_path(post.id) %>
    </li>
  <% end %>
  <% end %>
</ul>

app/views/contentful_posts/show.html.erb
<h1>Title - <%= @post.fields[:title] %></h1>

<p> Image Url - <%= @post.fields[:photo].fields[:url] %></p>

<h3> List Of Tags </h3>
<ul>
  <% @post.fields[:tags].each do |tag| %>
    <li>
      <%= tag.fields[:name]%>
    </li>
  <% end %>
</ul>

<h3> Content </h3>
<p> <%= @post.fields[:content]%> </p>

<% if @post.fields[:author] != nil %>
  <p> Author Name - <%= @post.fields[:author].fields[:name] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nayan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>